include:
  - path: .docker/docker-compose.yml
  - path: .ext/hmr_localisation/docker-compose.yml

# Service overrides
services:
  ros:
    volumes:
      - ./config/hmr_localisation/config:/ws/config
