/twist_mux:
  ros__parameters:
    use_stamped: false

    topics:
      teleop_joystick:
        topic: "/cmd_vel/joy"
        timeout: 0.5
        priority: 100
      teleop_keyboard:
        topic: "/cmd_vel/key"
        timeout: 0.5
        priority: 90
      navigation:
        topic: "/cmd_vel/nav"
        timeout: 1.0
        priority: 10

    locks:
      e_stop:
        topic: "/mux/e_stop"
        timeout: 0.0
        priority: 255