/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_pipeline_type: RGB
    right:
      i_publish_topic: false
    left:
      i_publish_topic: false
    rgb: 
      i_set_isp_scale: false