/**:
  ros__parameters:

    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_nn_type: none
      i_pipeline_type: RGB
      i_publish_tf_from_calibration: false
      i_enable_sync: false

    rgb:
      i_publish_topic: true
      i_sensor_img_orientation: ROTATE_180_DEG
      i_resolution: 1080P
      i_fps: 30.0
      i_publish_compressed: true
      i_rgb_low_bandwidth: true
      i_rgb_bandwidth_bitrate: 0
      i_rgb_bandwidth_ffmpeg_encoder: libx264
      i_rgb_bandwidth_frame_freq: 10
      i_rgb_bandwidth_profile: 4
      i_rgb_bandwidth_quality: 10

    stereo:
      i_publish_topic: false
      i_publish_left_rect: false
      i_publish_right_rect: false
      i_publish_synced_rect_pair: false
      i_output_disparity: false
      use_sim_time: false