# Copyright (c) Sensrad 2025

/**: #Wildcard namespace
  ros__parameters:
    # Geometries for perception
    vertical_height: 1.0 # Vertical height in meters of the radar installation above the ground
    radar_elevation_angle: 0.0 # Elevation angle [deg] of the radar boresight-ground. Positive angles defined upwards

    # Perception parameters
    perception_config: 0 # Perception configuration. 0: Dynamic default, 1: Static default
    cluster_scale: 1.0 # Scale factor for the clustering search radius
    free_space_max_range: 50.0 # Maximum considered range [m] for free space
    free_space_lower_bound: 0.4 # Lower bound [m] of interval relative estimated ground plane to calculate free space within.
    free_space_upper_bound: 3.0 # Upper bound [m] of interval relative estimated ground plane to calculate free space within.
    stationary_updates: 500 # Number of stationary updates before the tracker eliminates an object track
    region_of_interest: # Region of interest for the radar
      enabled: false # If true, the region of interest is used
      x_center: 0.0 # Center x-coordinate
      y_center: 100.0 # Center y-coordinate
      z_center: 0.0 # Center z-coordinate
      width: 100.0 # Width [m], or extension in x-direction, of the region of interest
      length: 200.0 # Length [m], or extension in y-direction, of the region of interest
      height: 100.0 # Height [m], or extension in z-direction, of the region of interest
      yaw: 0.0 # Yaw angle [rad] rotation around center coordinate
      pitch: 0.0 # Pitch angle [rad] rotation around center coordinate
