services:
  putn_nvidia:
    extends:
      file: docker-compose-gui.yaml
      service: putn
    environment:
     - NVIDIA_DRIVER_CAPABILITIES=all
     - __NV_PRIME_RENDER_OFFLOAD=1
     - __GLX_VENDOR_LIBRARY_NAME=nvidia
     - gpus=all
    runtime: nvidia