# --- Topic names ---
path_topic: "global_path"  # unused in debug mode
image_topic: "/debug/rgb"
depth_topic: "/debug/depth"
relative_depth_topic: "input_relative_depth"  # unused
path_publisher_topic: "/debug_projected_path"

# --- Debug ---
debug_project_only: true

# --- Frame IDs (no TF needed) ---
robot_frame: "camera_color_optical_frame"
world_frame: "camera_color_optical_frame"
camera_optical_frame: "camera_color_optical_frame"

# --- Image parameters ---
image_width: 640
image_height: 480

# --- Processing parameters ---
local_horizon_distance: 5.0
convert_depth_from_mm_to_m: false

# --- Camera intrinsics ---
camera_matrix:
  data: [612.9004516601562, 0.0, 321.5191345214844,
         0.0, 613.1563110351562, 276.79446411132812,
         0.0, 0.0, 1.0]

distortion_coefficients:
  data: [0.0, 0.0, 0.0, 0.0, 0.0]

robot_T_camera:
  data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]


debug_project_only: true

