services:
  xsens:
    build:
     context: .
     dockerfile: xsens/xsens-jetson.Dockerfile
    container_name: xsens
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/xsens-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/xsens/mtdevice.py:/root/ros2_ws/src/norlab_xsens_driver/xsens_driver/mtdevice.py:rw
      - ../sensor_configs/xsens/mtnode.py:/root/ros2_ws/src/norlab_xsens_driver/xsens_driver/mtnode.py:rw
      - ../sensor_configs/xsens/xsens_driver.launch.xml:/root/ros2_ws/src/norlab_xsens_driver/launch/xsens_driver.launch.xml:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/xsens-launch.sh

  emlid:
    build:
      context: .
      dockerfile: emlid/emlid-jetson.Dockerfile
    container_name: emlid
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/emlid-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/emlid/nmea_serial_driver.py:/root/ros2_ws/src/nmea_navsat_driver/src/libnmea_navsat_driver/nodes/nmea_serial_driver.py:rw
      - ../sensor_configs/emlid/nmea_serial_driver.yaml:/root/ros2_ws/src/nmea_navsat_driver/config/nmea_serial_driver.yaml:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/emlid-launch.sh

  oakd:
    build:
      context: .
      dockerfile: oakd/oakd-jetson.Dockerfile
    container_name: oakd
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/oakd-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      #Depthai ROS config
      - ../sensor_configs/oakd/depthai_ros_driver/config:/opt/ros/jazzy/share/depthai_ros_driver/config
      - ../sensor_configs/oakd/depthai_ros_driver/launch:/opt/ros/jazzy/share/depthai_ros_driver/launch
      #Depthai ROS V3 config
      #- ../sensor_configs/oakd/depthai_ros_driver/config/:/opt/ros/jazzy/share/depthai_ros_driver_v3/config/
      #- ../sensor_configs/oakd/depthai_ros_driver/launch/:/opt/ros/jazzy/share/depthai_ros_driver_v3/launch/
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/oakd-launch.sh

  hesai:
    build:
     context: .
     dockerfile: hesai/hesai-jetson.Dockerfile
    container_name: hesai
    privileged: true
    network_mode: host
    # ports:
    #   - "2368:2368/udp"
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/hesai-build:/root/ros2_ws/build
      - ../ros2_ws/src/HesaiLidar_ROS_2.0/:/root/ros2_ws/src/HesaiLidar_ROS_2.0/
      - ../shared_folder/:/root/shared_folder/
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/hesai-launch.sh

  atlas:
    build:
     context: .
     dockerfile: atlas/atlas-jetson.Dockerfile
    container_name: atlas
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/atlas-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/atlas:/root/shared_folder/atlas
      - ../ros2_ws/src/atlas/ros2_examples/src/ros2_aeva_publisher:/root/ros2_ws/src/ros2_aeva_publisher
      - ../ros2_ws/src/atlas/ros2_examples/src/aeva_msgs:/root/ros2_ws/src/aeva_msgs
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/atlas-launch.sh

  hugin:
    build:
     context: ..
     dockerfile: docker/hugin/hugin-jetson.Dockerfile
    container_name: hugin
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    network_mode: host
    # ports:
    #   - "6001:6001/udp"
    #   - "6003:6003/udp"
    #   - "6007:6007/udp"
    #   - "6010:6010/udp"
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/hugin-build:/opt/ros/overlay_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/hugin/ros2/src/:/opt/ros/overlay_ws/src/
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/hugin-launch.sh

  bunker:
    build:
      context: .
      dockerfile: bunker/bunker-jetson.Dockerfile
    container_name: bunker
    privileged: true
    network_mode: host
    volumes:
      - ../ros2_ws/build/bunker-build:/root/ros2_ws/build
      - ../ros2_ws/src/bunker_description:/root/ros2_ws/src/bunker_description
      
      - ../ros2_ws/src/bunker_ros2:/root/ros2_ws/src/bunker_ros2
      - ../ros2_ws/src/ugv_sdk:/root/ros2_ws/src/ugv_sdk

      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/bunker:/config/bunker
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/bunker-launch.sh

  recorder:
    build:
      context: .
      dockerfile: recorder/recorder-jetson.Dockerfile
    container_name: recorder
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../../rosbags/:/root/rosbags/
      - ../ros2_ws/build/recorder-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/atlas:/root/shared_folder/atlas
      - ../ros2_ws/src/atlas/ros2_examples/src/ros2_aeva_publisher:/root/ros2_ws/src/ros2_aeva_publisher
      - ../ros2_ws/src/atlas/ros2_examples/src/aeva_msgs:/root/ros2_ws/src/aeva_msgs
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/recorder-launch.sh

  visualizer:
    build:
      context: .
      dockerfile: visualizer/visualizer-jetson.Dockerfile
    container_name: visualizer
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    # ports:
    #   - "9092:9092"
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../../rosbags/:/root/rosbags/
      - ../ros2_ws/build/visualizer-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/atlas:/root/shared_folder/atlas
      - ../ros2_ws/src/atlas/ros2_examples/src/ros2_aeva_publisher:/root/ros2_ws/src/ros2_aeva_publisher
      - ../ros2_ws/src/atlas/ros2_examples/src/aeva_msgs:/root/ros2_ws/src/aeva_msgs
      - ../ros2_ws/src/bunker_description:/root/ros2_ws/src/bunker_description
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/visualizer-launch.sh

### NAVIGATION PIPELINE ###

  traversability_ros2:
    build:
     context: .
     dockerfile: traversability_mapping/traversability_mapping_ros2.Dockerfile
    container_name: trav_ros2
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/trav_ros2-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/traversability_mapping_ros2:/root/ros2_ws/src/traversability_mapping_ros2
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/trav_ros2-launch.sh

  glim:
    build:
     context: .
     dockerfile: glim/glim-jetson.Dockerfile
    container_name: glim
    privileged: true
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - /dev/:/dev/
      - ../../rosbags/:/root/rosbags/
      - ../ros2_ws/build/glim-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/glim/config:/glim_ws/src/glim/config
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/glim-launch.sh
  
  nav2:
    build:
      context: .
      dockerfile: nav2/nav2.Dockerfile
    container_name: nav2
    network_mode: host
    volumes:
      - ../ros2_ws/build/nav2-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/nav2:/root/nav2
      - ../sensor_configs/nav2/navigation_launch.py:/opt/ros/kilted/share/nav2_bringup/launch/navigation_launch.py:rw
      - ../sensor_configs/nav2/bringup_launch.py:/opt/ros/kilted/share/nav2_bringup/launch/bringup_launch.py:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/nav2-launch.sh

### Kalhan Algorithms

  hmr_localisation:
    build:
     context: .
     dockerfile: hmr_localisation/hmr.Dockerfile
    container_name: hmr_localisation
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/hmr-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/hmr_localisation/gt_ouster_ndt_tree.yaml:/root/ros2_ws/src/hmr_localisation/config/gt_ouster_ndt_tree.yaml:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/hmr-launch.sh

  scovox:
    build:
     context: .
     dockerfile: scovox/scovox.Dockerfile
    container_name: scovox
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/scovox-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/scovox/config:/root/ros2_ws/src/scovox/config
      - ../sensor_configs/explo_planner/config:/root/ros2_ws/src/explo_planner/config
      - ../sensor_configs/scovox/scovox_multi_robot.launch.py:/root/ros2_ws/src/scovox/src/scovox_mapping/launch/scovox_multi_robot.launch.py:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///root/shared_folder/cyclonedds-config.xml
    command: /root/shared_folder/scovox-launch.sh
