services:
  xsens:
    build:
     context: .
     dockerfile: xsens/xsens-jetson.Dockerfile
    container_name: xsens
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/xsens-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/xsens/mtdevice.py:/root/ros2_ws/src/norlab_xsens_driver/xsens_driver/mtdevice.py:rw
      - ../sensor_configs/xsens/mtnode.py:/root/ros2_ws/src/norlab_xsens_driver/xsens_driver/mtnode.py:rw
      - ../sensor_configs/xsens/xsens_driver.launch.xml:/root/ros2_ws/src/norlab_xsens_driver/launch/xsens_driver.launch.xml:rw
    environment:
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/xsens-launch.sh

  emlid:
    build:
      context: .
      dockerfile: emlid/emlid-jetson.Dockerfile
    container_name: emlid
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/emlid-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/emlid/nmea_serial_driver.py:/root/ros2_ws/src/nmea_navsat_driver/src/libnmea_navsat_driver/nodes/nmea_serial_driver.py:rw
      - ../sensor_configs/emlid/nmea_serial_driver.yaml:/root/ros2_ws/src/nmea_navsat_driver/config/nmea_serial_driver.yaml:rw
    environment:
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/emlid-launch.sh

  oakd:
    build:
      context: .
      dockerfile: oakd/oakd-jetson.Dockerfile
    container_name: oakd
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/oakd-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/oakd/depthai_ros_driver/config/:/opt/ros/jazzy/share/depthai_ros_driver_v3/config/
      - ../sensor_configs/oakd/depthai_ros_driver/launch/:/opt/ros/jazzy/share/depthai_ros_driver_v3/launch/
    environment:
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/oakd-launch.sh

  hesai:
    build:
     context: .
     dockerfile: hesai/hesai-jetson.Dockerfile
    container_name: hesai
    privileged: true
    network_mode: host
    # ports:
    #   - "2368:2368/udp"
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/hesai-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/hesai/config.yaml:/root/ros2_ws/src/HesaiLidar_ROS_2.0/config/config.yaml:rw
    environment:
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/hesai-launch.sh

  atlas:
    build:
     context: .
     dockerfile: atlas/atlas-jetson.Dockerfile
    container_name: atlas
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/atlas-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../shared_folder/atlas/ros2_examples/src/ros2_aeva_publisher:/root/ros2_ws/src/ros2_aeva_publisher
      - ../shared_folder/atlas/ros2_examples/src/aeva_msgs:/root/ros2_ws/src/aeva_msgs
    environment:
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/atlas-launch.sh

  hugin:
    build:
     context: ..
     dockerfile: docker/hugin/hugin-jetson.Dockerfile
    container_name: hugin
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    network_mode: host
    # ports:
    #   - "6001:6001/udp"
    #   - "6003:6003/udp"
    #   - "6007:6007/udp"
    #   - "6010:6010/udp"
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/hugin-build:/opt/ros/overlay_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../shared_folder/hugin/ros2/src/:/opt/ros/overlay_ws/src/
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/hugin-launch.sh

  bunker:
    build:
      context: .
      dockerfile: bunker/bunker-jetson.Dockerfile
    container_name: bunker
    privileged: true
    network_mode: host
    volumes:
      - ../ros2_ws/bunker-build:/root/ros2_ws/build
      - ../ros2_ws/bunker_description:/root/ros2_ws/src/bunker_description
      - ../shared_folder/:/root/shared_folder/
    environment:
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/bunker-launch.sh

  recorder:
    build:
      context: .
      dockerfile: recorder/recorder-jetson.Dockerfile
    container_name: recorder
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../../rosbags/:/root/rosbags/
      - ../ros2_ws/recorder-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../shared_folder/atlas/ros2_examples/src/ros2_aeva_publisher:/root/ros2_ws/src/ros2_aeva_publisher
      - ../shared_folder/atlas/ros2_examples/src/aeva_msgs:/root/ros2_ws/src/aeva_msgs
    environment:
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/recorder-launch.sh

  visualizer:
    build:
      context: .
      dockerfile: visualizer/visualizer-jetson.Dockerfile
    container_name: visualizer
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    # ports:
    #   - "9092:9092"
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../../rosbags/:/root/rosbags/
      - ../ros2_ws/visualizer-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../shared_folder/atlas/ros2_examples/src/ros2_aeva_publisher:/root/ros2_ws/src/ros2_aeva_publisher
      - ../shared_folder/atlas/ros2_examples/src/aeva_msgs:/root/ros2_ws/src/aeva_msgs
      - ../ros2_ws/bunker_description:/root/ros2_ws/src/bunker_description
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=42
    command: /root/shared_folder/visualizer-launch.sh
