lidar_topic: /rslidar_points
imu_topic: /madgwick_filtered_imu
lidar_type: Hesai
min_radius: 1
max_radius: 100
point_filter_num: 5
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.5
voxel_map_resolution: 0.5
max_iterations: 10

acc_cov: 0.01
gyr_cov: 0.0001
ba_cov: 0.000001
bg_cov: 0.000001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001


t_imu_lidar: [0.002, 0.006, 0.065]
R_imu_lidar: [0.9322978,  0.0000000,  0.3616916,
              0.0000000,  1.0000000,  0.0000000,
              -0.3616916,  0.0000000,  0.9322978]