lidar_topic: /ouster/points
imu_topic: /ouster/imu
lidar_type: ouster # velodyne ouster Hesai velodynem1600
min_radius: 1
max_radius: 30
point_filter_num: 5
time_scale: 0.000000001
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.5
voxel_map_resolution: 0.5
max_iterations: 10

acc_cov: 0.01
gyr_cov: 0.0001
ba_cov: 0.000001
bg_cov: 0.000001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001

t_imu_lidar: [-0.009725, 0.002441, -0.007533] # IMPORTANT: This is the translation from the LiDAR to the IMU frame, not the other way around!
R_imu_lidar: [1.0000000,  0.0000000,  0.0000000, # SAME HERE
              0.0000000,  1.0000000,  0.0000000,
              0.0000000,  0.0000000,  1.0000000]
