# Copyright (c) Sensrad 2025

/**:
  ros__parameters:
    ip: 10.20.30.40 # IP address of the radar
    data_port: 6003 # Port that the radar sends point-cloud to (default UDP)
    ctrl_port: 6001 # Port that the radar sends control messages to (default TCP)
    log_port: 6010 # Port that the radar sends log messages to (default TCP)
    someip_port: 6007 # Port that the radar uses for SOME/IP communication (default TCP)
    ptp_is_active: false # If true, Hugin D1 radar acts as a PTP follower and the manual time synchronization in ROS2 and Hugin Control GUI is disabled.
    auto_start_tx: false # If true, the radar starts sending data automatically when the radar is connected
    frame_id: "radar_1" # ROS frame ID for the radar
    fw_version: 2.10.5 # Firmware version of the radar
