map:
  resolution: 0.4
  map_x_l: -420.0
  map_x_u: 420.0
  map_y_l: -420.0
  map_y_u: 420.0

planning: 
  step_size: 0.4
  h_surf_car: 0.6

  radius_fit_plane: 0.8

  w_flatness: 800.0
  w_slope: 0.02
  w_sparsity: 0.05
  w_fit_plane: 0.2
  ratio_max: 0.3
  ratio_min: 0.01
  conv_thre: 0.5152

  max_initial_time: 15000.0


